Repository UniversityOfSaskatchewanCMPT371/term-project-2024-team-3, pull requests merged in 2024-01, with the labels that each got.

#3 CI Pipeline Setup
  .github/workflows/main.yml
Labels: build, ID1

#29 Install linter and prettier and implement with pre commit hooks
  .husky/pre-commit
  frontend/.eslintrc.json
  frontend/.prettierignore
  frontend/.prettierrc.json
  frontend/package.json
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/index.tsx
  frontend/src/reportWebVitals.ts
  frontend/src/setupTests.ts
  frontend/yarn.lock
Labels: build, ID1

#30 Setup file upload page
  frontend/src/FileUploadPage/FileUpload.module.css
  frontend/src/FileUploadPage/FileUploadPage.test.tsx
  frontend/src/FileUploadPage/FileUploadPage.tsx
  frontend/src/FileUploadPage/components/FileDropzone.test.tsx
  frontend/src/FileUploadPage/components/FileDropzone.tsx
  frontend/src/FileUploadPage/components/FileDropzoneControls.test.tsx
  frontend/src/FileUploadPage/components/FileDropzoneControls.tsx
  frontend/src/Routes/Routes.tsx
Labels: enhancement, ID1

#37 24 process data page
  frontend/src/App.tsx
  frontend/src/ProcessDataPage/ProcessedDataPage.module.css
  frontend/src/ProcessDataPage/ProcessedDataPage.test.tsx
  frontend/src/ProcessDataPage/ProcessedDataPage.tsx
  frontend/src/pages/TestPage.tsx
Labels: build, ID1

#38 22 setup home page
  frontend/src/App.tsx
  frontend/src/Home.tsx
  frontend/src/HomePage/HomePage.module.css
  frontend/src/HomePage/HomePage.test.tsx
  frontend/src/HomePage/HomePage.tsx
  frontend/src/assets/AppleWatch.pdf
  frontend/src/assets/Fitbit.pdf
  frontend/src/assets/beap_lab_hex_small.jpg
  frontend/src/assets/consent.pdf
  frontend/src/assets/engine-overview.png
  frontend/src/global.d.ts
  frontend/tsconfig.json
Labels: enhancement, ID1

#72 Branch Naming Conventions
  README.md
  documents/assets/image-1.png
  documents/assets/image-2.png
  documents/assets/image.png
Labels: documentation, ID 2

#74 Added pr templates
  .github/pull_request_template.md
Labels: documentation

#73 Installed Rollbar
  frontend/package.json
  frontend/yarn.lock
Labels: build, ID2
