Repository UniversityOfSaskatchewanCMPT371/term-project-2024-team-3, pull requests merged in 2024-03, with the labels that each got.

#188 Setup TLS
  Dockerfile.prod
  backend/Dockerfile
  docker-compose-prod.yml
  frontend/package.json
  frontend/src/shared/api/baseapi.ts
  tomcat-config/server.xml
  tomcat-config/web.xml
Labels: build, ID4

#190 Uploading Files Smoke Tst
  frontend/package.json
  frontend/src/pages/FileUploadPage/components/FileDropzone.tsx
  frontend/tests_end2end/FileUploadPage.spec.ts
  frontend/tests_end2end/Navbar.spec.ts
  frontend/tests_end2end/PredictedDataPage.spec.ts
  frontend/tests_end2end/util/setupMockLogin.ts
  frontend/tests_end2end/utils.ts
Labels: ID4, QA

#191 Fixed the white screen bug
  frontend/src/shared/hooks/useIsUserLoggedIn.ts
  frontend/src/shared/hooks/useIsUserLoggedin.test.ts
Labels: bug, ID4

#189 Setup backend testing
  .github/workflows/backend.yml
  .github/workflows/digitalocean_deploy.yml
  .github/workflows/frontend.yml
  .github/workflows/playwright.yml
  README.md
  backend/pom.xml
  backend/r-requirements/requirements-src.R
  backend/src/main/java/com/beaplab/BeaplabEngine/controller/HomeController.java
  backend/src/main/java/com/beaplab/BeaplabEngine/controller/UserController.java
  backend/src/test/java/controllers/HomeControllerTest.java
Labels: build, ID4

#201 Build improvements
  docker-compose-prod.yml
  frontend/.eslintrc.json
  frontend/package.json
  tomcat-config/server.xml
  tomcat-config/web.xml
Labels: build, ID4

#210 Add code coverage
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
  backend/pom.xml
  backend/src/test/java/controllers/HomeControllerTest.java
Labels: build, QA

#217 User Service Test setup
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
  .github/workflows/playwright.yml
  README.md
  backend/pom.xml
  backend/src/main/java/com/beaplab/BeaplabEngine/service/UserService.java
  backend/src/main/java/com/beaplab/BeaplabEngine/util/Util.java
  backend/src/test/java/controllers/HomeControllerTest.java
  backend/src/test/java/service/UserServiceTest.java
  backend/src/test/java/utils/MockFactory.java
  backend/src/test/java/utils/TestHelper.java
  backend/src/test/java/utils/UtilTest.java
Labels: ID4, QA

#231 Test/203 incorect logins service
  backend/src/main/java/com/beaplab/BeaplabEngine/service/IncorrectLoginsService.java
  backend/src/test/java/service/IncorrectLoginsServiceTest.java
  backend/src/test/java/utils/MockFactory.java
Labels: test, ID4, QA

#236 Increase coverage
  backend/pom.xml
  backend/src/test/java/service/UserServiceTest.java
  frontend/package.json
  frontend/src/ProcessedFiles.tsx
  frontend/src/components/Authentication/ProtectedRoute.test.tsx
  frontend/src/components/Authentication/useAuth.test.tsx
  frontend/src/components/Authentication/useAuth.tsx
  frontend/src/pages/LoginPage/components/LoginForm.tsx
  frontend/src/shared/Data/index.test.ts
  frontend/src/shared/Data/index.ts
Labels: ID4, QA

#238 added comments, assertions, and logging
  frontend/src/pages/FileUploadPage/FileUploadPage.tsx
  frontend/src/pages/FileUploadPage/components/FileDropzone.tsx
Labels: ID4, QA

#241 Qa/239 playwright improvements
  frontend/src/shared/hooks/useLogout.test.ts
  frontend/src/shared/hooks/useLogout.ts
  frontend/tests_end2end/Navbar.spec.ts
  frontend/tests_end2end/ProcessDataPage.spec.ts
Labels: ID4, QA

#271 Revert running on only files changed
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
Labels: bug, build

#275 Added ProgressBarType to export for progress bar
  frontend/src/components/ProgressBar/ProgressBar.test.tsx
  frontend/src/components/ProgressBar/ProgressBar.tsx
  frontend/src/pages/ProcessDataPage/ProcessedDataPage.tsx
  frontend/src/shared/api/types.ts
  frontend/src/shared/hooks/useDownload.test.ts
  frontend/src/shared/hooks/useDownload.ts
Labels: ID5

#273 130 complete file upload page functionality
  frontend/package.json
  frontend/public/beap_lab_hex_small.jpg
  frontend/public/beap_lab_hex_small.png
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/src/components/ErrorSnackbar/ErrorSnackbar.test.tsx
  frontend/src/components/ErrorSnackbar/ErrorSnackbar.tsx
  frontend/src/components/Icons/index.tsx
  frontend/src/pages/FileUploadPage/FileUpload.module.css
  frontend/src/pages/FileUploadPage/FileUploadPage.test.tsx
  frontend/src/pages/FileUploadPage/FileUploadPage.tsx
  frontend/src/pages/FileUploadPage/components/FileDropzone.test.tsx
  frontend/src/pages/FileUploadPage/components/FileDropzone.tsx
  frontend/src/pages/FileUploadPage/components/FileDropzoneControls.tsx
  frontend/src/pages/FileUploadPage/components/UploadedFiles.module.css
  frontend/src/pages/FileUploadPage/components/UploadedFiles.test.tsx
  frontend/src/pages/FileUploadPage/components/UploadedFiles.tsx
  frontend/src/shared/Data/index.ts
  frontend/src/shared/api/types.ts
  frontend/src/shared/hooks/useGetUploadedFiles.test.ts
  frontend/src/shared/hooks/useGetUploadedFiles.ts
  frontend/src/shared/hooks/useProcessFile.test.ts
  frontend/src/shared/hooks/useProcessFile.ts
  frontend/src/shared/hooks/useUpload.test.ts
  frontend/src/shared/hooks/useUpload.ts
  frontend/tests_end2end/FileUploadPage.spec.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: enhancement, ID5

#284 Initialize data db
  backend/db-scripts/init.sql
Labels: build

#292 165/generalize watch service
  backend/src/main/java/com/beaplab/BeaplabEngine/controller/AppleWatchController.java
  backend/src/main/java/com/beaplab/BeaplabEngine/controller/FitbitController.java
  backend/src/main/java/com/beaplab/BeaplabEngine/controller/WatchController.java
  backend/src/main/java/com/beaplab/BeaplabEngine/service/AppleWatchService.java
  backend/src/main/java/com/beaplab/BeaplabEngine/service/FitbitService.java
  backend/src/main/java/com/beaplab/BeaplabEngine/service/interfaces/WatchService.java
  backend/src/main/java/com/beaplab/BeaplabEngine/util/ArchiveUtil.java
  backend/src/main/java/com/beaplab/BeaplabEngine/util/DownloadUtil.java
  backend/src/test/java/controller/WatchControllerTest.java
  backend/src/test/java/utils/MockFactory.java
  frontend/src/pages/ProcessDataPage/ProcessedDataPage.tsx
  frontend/src/shared/Data/index.ts
  frontend/src/shared/api/types.ts
Labels: ID5, backend

#294 Production Setup Documentation and Troubleshooting
  README.md
  documents/build/README.md
  frontend/README.md
Labels: documentation

#297 Qa/249 playwright smoke test
  .github/workflows/digitalocean_deploy.yml
  .github/workflows/playwright_smoke.yml
  frontend/playwright.config.ts
  frontend/src/shared/hooks/useLogin.test.ts
  frontend/src/shared/hooks/useLogin.ts
  frontend/tests_end2end/SmokeTest.spec.ts
Labels: ID5, QA

#302 Hotfix/301 fix redis security issue
  .github/workflows/digitalocean_deploy.yml
  backend/src/main/java/com/beaplab/BeaplabEngine/config/RedisConfig.java
  backend/src/main/resources/redis.properties
  docker-compose-prod.yml
  docker-compose-staging.yml
  docker-compose.yml
Labels: bug, build

#299 Bug/293 properly error handling
  frontend/src/components/LoadingModal/LoadingModal.test.tsx
  frontend/src/components/LoadingModal/LoadingModal.tsx
  frontend/src/components/LoadingModal/loading-modal.css
  frontend/src/components/LoadingSpinner/LoadingSpinner.css
  frontend/src/components/LoadingSpinner/LoadingSpinner.tsx
  frontend/src/components/Navbar/Navbar.module.css
  frontend/src/components/Navbar/Navbar.test.tsx
  frontend/src/components/Navbar/Navbar.tsx
  frontend/src/shared/Data/index.ts
  frontend/src/shared/hooks/useDeleteFile.test.ts
  frontend/src/shared/hooks/useDeleteFile.ts
  frontend/src/shared/hooks/useDownload.ts
  frontend/src/shared/hooks/useGetPredictedDataList.ts
  frontend/src/shared/hooks/useGetProcessedDataList.ts
  frontend/src/shared/hooks/useGetUploadedFiles.ts
  frontend/src/shared/hooks/useLogin.test.ts
  frontend/src/shared/hooks/useLogin.ts
  frontend/src/shared/hooks/useLogout.test.ts
  frontend/src/shared/hooks/useLogout.ts
  frontend/src/shared/hooks/usePredictFile.test.ts
  frontend/src/shared/hooks/usePredictFile.ts
  frontend/src/shared/hooks/useProcessFile.ts
  frontend/src/shared/hooks/useSignup.test.ts
  frontend/src/shared/hooks/useSignup.ts
  frontend/src/shared/hooks/useUpload.ts
Labels: bug

#290 Feature/255 user profile
  backend/db-scripts/init.sql
  backend/src/main/java/com/beaplab/BeaplabEngine/config/AppConfig.java
  backend/src/main/java/com/beaplab/BeaplabEngine/controller/LoginUserController.java
  backend/src/main/java/com/beaplab/BeaplabEngine/controller/UserController.java
  backend/src/main/java/com/beaplab/BeaplabEngine/metadata/UpdatePasswordObject.java
  backend/src/main/java/com/beaplab/BeaplabEngine/repository/AccessGroupDao.java
  backend/src/main/java/com/beaplab/BeaplabEngine/repository/PredictedDataDao.java
  backend/src/main/java/com/beaplab/BeaplabEngine/repository/ProcessedDataDao.java
  backend/src/main/java/com/beaplab/BeaplabEngine/repository/RawDataDao.java
  backend/src/main/java/com/beaplab/BeaplabEngine/repository/RoleDao.java
  backend/src/main/java/com/beaplab/BeaplabEngine/repository/UserDao.java
  backend/src/main/java/com/beaplab/BeaplabEngine/service/PredictedDataService.java
  backend/src/main/java/com/beaplab/BeaplabEngine/service/ProcessedDataService.java
  backend/src/main/java/com/beaplab/BeaplabEngine/service/ProfileDeleteService.java
  backend/src/main/java/com/beaplab/BeaplabEngine/service/RawDataService.java
  backend/src/main/java/com/beaplab/BeaplabEngine/service/UserService.java
  backend/src/test/java/controller/UserControllerTest.java
  backend/src/test/java/repository/PredictedDataDaoTest.java
  backend/src/test/java/repository/ProcessedDataDaoTest.java
  backend/src/test/java/repository/RawDataDaoTest.java
  backend/src/test/java/repository/UseDaoTest.java
  backend/src/test/java/service/PredictedDataServiceTest.java
  backend/src/test/java/service/ProcessedDataServiceTest.java
  backend/src/test/java/service/RawDataServiceTest.java
  backend/src/test/java/service/UserServiceTest.java
  docker-compose.yml
  frontend/src/App.tsx
  frontend/src/components/ConfirmModal/ConfirmModal.test.tsx
  frontend/src/components/ConfirmModal/ConfirmModal.tsx
  frontend/src/components/ConfirmModal/confirm-modal.css
  frontend/src/components/Icons/index.test.tsx
  frontend/src/components/Icons/index.tsx
  frontend/src/components/Navbar/Navbar.module.css
  frontend/src/components/Navbar/Navbar.test.tsx
  frontend/src/components/Navbar/Navbar.tsx
  frontend/src/components/Navbar/components/ProfileMenu.test.tsx
  frontend/src/components/Navbar/components/ProfileMenu.tsx
  frontend/src/pages/HomePage/HomePage.tsx
  frontend/src/pages/ProfilePage/ProfilePage.test.tsx
  frontend/src/pages/ProfilePage/ProfilePage.tsx
  frontend/src/pages/ProfilePage/profile.css
  frontend/src/shared/api/Api.test.tsx
  frontend/src/shared/api/Api.ts
  frontend/src/shared/api/types.ts
  frontend/src/shared/hooks/useChangePassword.test.ts
  frontend/src/shared/hooks/useChangePassword.ts
  frontend/src/shared/hooks/useDeleteAccount.test.ts
  frontend/src/shared/hooks/useDeleteAccount.ts
  frontend/src/shared/hooks/useDeleteData.test.ts
  frontend/src/shared/hooks/useDeleteData.ts
  frontend/src/shared/hooks/useGetUser.test.ts
  frontend/src/shared/hooks/useGetUser.ts
  frontend/tests_end2end/SmokeTest.spec.ts
Labels: feature, ID5

#308 Qa/251 role controler testing
  backend/src/main/java/com/beaplab/BeaplabEngine/controller/RoleController.java
  backend/src/test/java/controller/RoleControllerTest.java
Labels: test, ID5, QA
