Repository UniversityOfSaskatchewanCMPT371/term-project-2024-team-3, pull requests merged in 2024-02, with the labels that each got.

#78 Setup docker containers
  README.md
  backend/Dockerfile
  backend/db-scripts/init.sql
  backend/src/main/resources/postgresql.properties
  backend/src/main/resources/redis.properties
  docker-compose.yml
  frontend/.dockerignore
  frontend/Dockerfile
Labels: build, ID2

#79 moved playwright.yml for ci integration
  .github/workflows/playwright.yml
Labels: build, ID 2

#82 improved CI pipeline, renaming and updating
  .github/workflows/frontend.yml
Labels: build, ID 2

#84 Spike/83 playwright navbar example
  frontend/playwright.config.ts
  frontend/tests_end2end/HomePage.spec.ts
  frontend/tests_end2end/Navbar.spec.ts
  frontend/tests_end2end/example.spec.ts
  frontend/tsconfig.json
Labels: spike, ID2, test

#89 Fix DB and Connected R repo
  backend/DatabaseBackups/PostgresFunctions.txt
  backend/Dockerfile
  backend/db-scripts/init.sql
  backend/r-requirements/requirements-src.R
  backend/src/main/java/com/beaplab/BeaplabEngine/model/PredictedDataIndex.java
  backend/src/main/java/com/beaplab/BeaplabEngine/model/ProcessedDataIndex.java
  backend/src/main/java/com/beaplab/BeaplabEngine/model/RawData.java
  backend/src/main/java/com/beaplab/BeaplabEngine/model/RawDataIndex.java
  backend/src/main/java/com/beaplab/BeaplabEngine/service/RawDataService.java
  backend/src/main/resources/r_repo.properties
  docker-compose.yml
Labels: build, ID2

#94 Feature/75 file upload page functionality
  frontend/src/pages/FileUploadPage/components/FileDropzone.test.tsx
  frontend/src/pages/FileUploadPage/components/FileDropzone.tsx
  frontend/src/pages/FileUploadPage/components/FileDropzoneControls.test.tsx
  frontend/src/pages/FileUploadPage/components/FileDropzoneControls.tsx
Labels: enhancement, ID2, feature

#105 fixed the href for the button
  frontend/src/pages/ProcessDataPage/ProcessedDataPage.tsx
Labels: bug

#106 Test/102 basic playwright UI tests
  frontend/tests_end2end/FileUploadPage.spec.ts
  frontend/tests_end2end/PredictedDataPage.spec.ts
  frontend/tests_end2end/ProcessDataPage.spec.ts
Labels: ID2, test

#114 ID2 Handin
  documents/ID2/Designs/FileUpload Page/FileUploadPage2.png
  documents/ID2/Designs/SignupAndLogin Page/BEAPENGINE - User Flow, design and Implementation considerations.png
  documents/ID2/Designs/SignupAndLogin Page/BEAPENGINE LOGIN PAGE.png
  documents/ID2/Designs/SignupAndLogin Page/BEAPENGINE SIGNUP PAGE.png
  documents/ID2/ID2-Test-QA Documents/General Testing Matrix.pdf
  documents/ID2/ID2-Test-QA Documents/Test Matrix _ Requirement - Test Cases.pdf
  documents/ID2/ID2-Test-QA Documents/Testing Strategy (Updated including test smokes) - Team 3.pdf
  documents/ID2/ID2-_Activity_Report.pdf
  documents/ID2/ID2-_Attendance_for_meetings.pdf
  documents/ID2/ID2-_Documentation_of_team_personnel_roles.pdf
  documents/ID2/ID2-_Retrospective.pdf
  documents/ID2/ID2-_Update_for_Software_Requirements.pdf
  documents/ID2/ID2_Assigned_Tasks.pdf
  documents/ID2/ID2_Meetings_with_stakeholder_Documentation.pdf
  documents/ID2/ID2_Mini-milestone_list.pdf
  documents/ID2/ID2_Rollbar_Spike.pdf
  documents/ID2/ID2_Tutorials_given_within_the_team_and_other_investments_in_spreading_knowledge.pdf
  documents/ID2/Incremental_Deliverable_2_Risk_Report.pdf
  documents/ID2/Inspections and Checklists/97-FileUploadPage Code Inspection.pdf
  documents/ID2/Inspections and Checklists/97-HomePage Code Inspection.pdf
  documents/ID2/Inspections and Checklists/App_inspection_checklist.pdf
  documents/ID2/Inspections and Checklists/Check_list_for_Docker_Inspection.pdf
  documents/ID2/Inspections and Checklists/FileDropZoneControls_code_inspection_checklist.pdf
  documents/ID2/Inspections and Checklists/FileDropZone_code_inspection_checklist.pdf
  documents/ID2/Inspections and Checklists/HomePage.spec_inspection_checklist.pdf
  documents/ID2/Inspections and Checklists/ID2_Peer_Reviews_Inspections_36c115ed992a429f9e291bc315777ec3.pdf
  documents/ID2/Inspections and Checklists/NavBar_inspection_checklist.pdf
  documents/ID2/Inspections and Checklists/PredictedDataPage_code_inspection_checklist.pdf
  documents/ID2/Inspections and Checklists/ProcessDataPage_code_inspection_checklist.pdf
  documents/ID2/Inspections and Checklists/Team3_FileUploadPage_CodeReviewChecklist_-_Sheet1.pdf
  documents/ID2/Plan_for_ID3.pdf
  documents/ID2/Software Diagrams/Component_Diagram.pdf
  documents/ID2/Software Diagrams/fileupload_activity_diagram.jpg
Labels: documentation, ID2

#139 Automated deployment set up
  .github/workflows/digitalocean_deploy.yml
  .github/workflows/playwright.yml
  Dockerfile.prod
  docker-compose-prod.yml
Labels: build, ID3

#145 121 implement authcontext for user authentication in react with typescript
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Authentication/ProtectedRoute.tsx
  frontend/src/components/Authentication/useAuth.tsx
  frontend/src/components/Navbar/Navbar.tsx
  frontend/src/pages/LoginPage/components/LoginForm.tsx
  frontend/src/shared/api/Api.test.tsx
  frontend/src/shared/api/Api.ts
  frontend/src/shared/api/index.ts
  frontend/src/shared/api/types.ts
  frontend/src/shared/hooks/useIsUserLoggedIn.ts
  frontend/src/shared/hooks/useIsUserLoggedin.test.ts
  frontend/src/shared/hooks/useLogin.test.ts
  frontend/src/shared/hooks/useLogin.ts
  frontend/src/shared/hooks/useLogout.test.ts
  frontend/src/shared/hooks/useLogout.ts
  frontend/src/shared/hooks/useSignup.test.ts
  frontend/src/shared/hooks/useSignup.ts
  frontend/tests_end2end/FileUploadPage.spec.ts
  frontend/tests_end2end/Navbar.spec.ts
  frontend/tests_end2end/PredictedDataPage.spec.ts
  frontend/tests_end2end/ProcessDataPage.spec.ts
  frontend/tests_end2end/util/setupMockLogin.ts
  frontend/yarn.lock
Labels: feature, ID3

#147 144 reusable help popup
  .github/workflows/digitalocean_deploy.yml
  .github/workflows/playwright.yml
  Dockerfile.prod
  docker-compose-prod.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/HelpPopup/HelpPopup.module.css
  frontend/src/components/HelpPopup/HelpPopup.test.tsx
  frontend/src/components/HelpPopup/HelpPopup.tsx
  frontend/tests_end2end/FileUploadPage.spec.ts
  frontend/yarn.lock
Labels: feature, ID3

#148 Change base URL based on environment
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/shared/api/Api.test.tsx
  frontend/src/shared/api/Api.ts
  frontend/src/shared/api/baseapi.ts
  frontend/tsconfig.json
Labels: build, ID3

#156 Secured sensitive credentials in app
  .github/workflows/digitalocean_deploy.yml
  .gitignore
  Dockerfile.prod
  backend/Dockerfile
  backend/src/main/resources/postgresql.properties
  backend/src/main/resources/r_repo.properties
  docker-compose-prod.yml
  docker-compose.yml
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/components/HelpPopup/HelpPopup.test.tsx
  frontend/src/components/HelpPopup/HelpPopup.tsx
  frontend/src/pages/FileUploadPage/FileUploadPage.test.tsx
  frontend/src/pages/FileUploadPage/FileUploadPage.tsx
  frontend/src/pages/FileUploadPage/components/FileDropzone.test.tsx
  frontend/src/pages/FileUploadPage/components/FileDropzone.tsx
  frontend/src/pages/HomePage/HomePage.test.tsx
  frontend/src/pages/HomePage/HomePage.tsx
  frontend/src/pages/PredictedDataPage/PredictedDataPage.test.tsx
  frontend/src/pages/PredictedDataPage/PredictedDataPage.tsx
  frontend/src/pages/ProcessDataPage/ProcessedDataPage.test.tsx
  frontend/src/pages/ProcessDataPage/ProcessedDataPage.tsx
  frontend/src/shared/api/baseapi.ts
  frontend/src/shared/config/rollbar.ts
  frontend/src/shared/util/tests/render.tsx
Labels: build, ID3

#157 Fix SPA Routing
  .DS_Store
  .gitignore
  Dockerfile.prod
  README.md
  backend/.DS_Store
  backend/src/.DS_Store
  frontend/tomcat-config/web.xml
  services/.DS_Store
  services/ml-service/.DS_Store
Labels: bug

#159 118 implement UI for processed data page
  frontend/src/pages/ProcessDataPage/ProcessedDataPage.module.css
  frontend/src/pages/ProcessDataPage/ProcessedDataPage.test.tsx
  frontend/src/pages/ProcessDataPage/ProcessedDataPage.tsx
  frontend/src/shared/api/baseapi.ts
  frontend/src/shared/hooks/useDeleteFile.test.ts
  frontend/src/shared/hooks/useGetProcessedDataList.test.ts
  frontend/src/shared/hooks/useGetProcessedDataList.ts
  frontend/src/shared/hooks/useGetUploadedFiles.test.ts
  frontend/src/shared/hooks/useGetUploadedFiles.ts
  frontend/src/shared/hooks/usePredictFile.test.ts
  frontend/src/shared/hooks/usePredictFile.ts
Labels: feature, ID3

#160 Feature/130 complete file upload page
  frontend/src/pages/FileUploadPage/FileUpload.module.css
  frontend/src/pages/FileUploadPage/FileUploadPage.test.tsx
  frontend/src/pages/FileUploadPage/FileUploadPage.tsx
  frontend/src/pages/FileUploadPage/components/FileDropzone.test.tsx
  frontend/src/pages/FileUploadPage/components/FileDropzone.tsx
  frontend/src/pages/FileUploadPage/components/FileDropzoneControls.test.tsx
  frontend/src/pages/FileUploadPage/components/FileDropzoneControls.tsx
  frontend/src/shared/Data/index.ts
  frontend/src/shared/hooks/useUpload.test.ts
  frontend/src/shared/hooks/useUpload.ts
Labels: feature, ID3
