Repository UniversityOfSaskatchewanCMPT371/term-project-2024-team-3, pull requests merged in 2024-04, with the labels that each got.

#310 fixed/ updated the smoke test
  frontend/tests_end2end/SmokeTest.spec.ts
Labels: ID5, QA

#312 311 redirect issue
  frontend/src/components/Authentication/ProtectedRoute.test.tsx
  frontend/src/components/Authentication/ProtectedRoute.tsx
Labels: bug, ID5

#314 Bug/313 fix bugs
  frontend/src/components/Navbar/components/ProfileMenu.test.tsx
  frontend/src/pages/FileUploadPage/components/FileDropzone.test.tsx
  frontend/src/pages/ProfilePage/ProfilePage.test.tsx
  frontend/src/pages/ProfilePage/ProfilePage.tsx
  frontend/src/shared/api/Api.test.tsx
  frontend/src/shared/api/Api.ts
  frontend/src/shared/api/types.ts
  frontend/src/shared/hooks/useGetUser.test.ts
  frontend/src/shared/hooks/useGetUser.ts
Labels: bug

#318 fix playwright tests
  frontend/tests_end2end/FileUploadPage.spec.ts
  frontend/tests_end2end/HomePage.spec.ts
  frontend/tests_end2end/Navbar.spec.ts
  frontend/tests_end2end/PredictedDataPage.spec.ts
  frontend/tests_end2end/ProcessDataPage.spec.ts
  frontend/tests_end2end/SmokeTest.spec.ts
  frontend/tests_end2end/utils.ts
Labels: ID5, QA

#321 prevent source maps generation
  .github/workflows/playwright.yml
  .github/workflows/playwright_smoke.yml
  frontend/package.json
  frontend/yarn.lock
Labels: build

#320 fixed stability issues with the playwright tests
  frontend/tests_end2end/FileUploadPage.spec.ts
  frontend/tests_end2end/utils.ts
Labels: bug
